[package]
name = "underpass-turbo"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
osm_pbf_iter = { path = "../rust-osm-pbf-iter" } # "~0.1.0"
clap = "2.20.5"
threadpool = "1.7"
regex = "1"
